import type { Metadata } from "next";
import { Inter } from "next/font/google";

import "./globals.css";
import { RecoilRoot } from "recoil";
import RootComponents from "@/components/RootComponent";
import Navbar from "@/components/Layout/Navbar";
import SideBar from "@/components/Layout/SideBar";
import SwitchTheme from "@/components/SwitchTheme";

const inter = Inter({ subsets: ["latin"] });

// write me function that will

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="bg-base-200 emerald">
      <RootComponents>
        <body className={inter.className}>
          <Navbar />
          <SideBar />
          {children}
          <div className="absolute top-4 right-4 z-10">
            <SwitchTheme />
          </div>
        </body>
      </RootComponents>
    </html>
  );
}
